global using System;
global using System.Buffers;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.IO;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Data;
global using System.Net;
global using System.Reflection;
global using System.Globalization;
global using System.Diagnostics;
global using System.Linq;
global using System.Security.Cryptography;
global using System.Runtime.CompilerServices;
global using System.Runtime.Serialization;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Concurrent;
global using System.Collections.Frozen;
global using System.Collections.Immutable;
global using System.Collections.Specialized;
global using System.Collections.ObjectModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Threading;
global using System.Threading.Tasks;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using Newtonsoft.Json.Serialization;
global using System.Drawing;
global using System.IO.Compression;
global using System.IO.Hashing;
global using System.Linq.Expressions;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Net.Security;
global using System.Numerics;
global using System.Reflection.Emit;
global using System.Runtime.InteropServices;
global using System.Security;
global using System.Threading.Tasks.Dataflow;
global using System.Web;
global using System.Windows.Input;
global using Nito.Collections;
global using JetBrains.Annotations;
global using ValueOf;
global using CommunityToolkit.Diagnostics;
global using Jakar.Extensions.Loggers;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options; 
global using OneOf;
global using OneOf.Types;
global using static Jakar.Extensions.BaseRecord;
global using static Jakar.Extensions.Buffers;
global using static Jakar.Extensions.Claims;
global using static Jakar.Extensions.WebRequester;
global using ErrorEventArgs = System.IO.ErrorEventArgs;


/*
global using System.Text.Json;
global using System.Text.Json.Nodes;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using MsJsonConverterAttribute = System.Text.Json.Serialization.JsonConverterAttribute;
global using MsJsonExtensionDataAttribute = System.Text.Json.Serialization.JsonExtensionDataAttribute;
global using MsJsonIgnoreAttribute = System.Text.Json.Serialization.JsonIgnoreAttribute;
global using MsJsonSerializer = System.Text.Json.JsonSerializer;
global using MsJsonSerializerOptions = System.Text.Json.JsonSerializerOptions;
*/
