// Jakar.Json.Generator
// 10/07/2026

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;



namespace Jakar.Json.Generator;


internal static class Emitter
{
    private const string J = "global::Jakar.Json.";
    private const string C = "global::Jakar.Json.Converters.";
    private const string R = "TReader";
    private const string W = "TWriter";



    /// <summary> A member ready to emit: its resolved settings, JSON name and converter. </summary>
    private sealed record Resolved( MemberInfo Member,
                                    int        Index,
                                    Settings   Settings,
                                    string     JsonName,
                                    string     Converter,
                                    bool       Required,
                                    bool       Bound,
                                    string     Local )
    {
        public string Name => Member.Name;
    }



    // ─── Entry points ────────────────────────────────────────────────────────

    public static IEnumerable<EnumInfo> EnumsUsed( ModelInfo model, Settings defaults )
    {
        if ( model.IsFatal ) { yield break; }

        Settings type = defaults.With(model.Settings);

        foreach ( MemberInfo member in model.Members )
        {
            if ( member.Converter is not null || member.IsExtensionData ) { continue; }

            foreach ( EnumInfo info in Enums(member.Shape, type.With(member.Settings)) ) { yield return info; }
        }
    }

    private static IEnumerable<EnumInfo> Enums( TypeShape shape, Settings settings )
    {
        if ( shape is { Kind: ShapeKind.Enum, Enum: { } info } && settings.Enums != Values.ENUMS_NUMBER ) { yield return TypeShapes.WithNaming(info, settings.EnumNaming); }

        if ( shape.Key is { Kind: ShapeKind.Enum, Enum: { } key } ) { yield return TypeShapes.WithNaming(key, settings.EnumNaming); }

        if ( shape.Element is not null )
        {
            foreach ( EnumInfo nested in Enums(shape.Element, settings) ) { yield return nested; }
        }
    }


    public static void EmitModel( SourceProductionContext spc, ModelInfo model, Settings defaults )
    {
        foreach ( DiagnosticInfo diagnostic in model.Diagnostics ) { spc.ReportDiagnostic(diagnostic.ToDiagnostic()); }

        if ( model.IsFatal ) { return; }

        Settings       type    = defaults.With(model.Settings);
        List<Resolved> members = Resolve(model, type, out MemberInfo? extension, out List<DiagnosticInfo> problems);
        foreach ( DiagnosticInfo problem in problems ) { spc.ReportDiagnostic(problem.ToDiagnostic()); }

        if ( problems.Any(static p => p.Descriptor.DefaultSeverity == DiagnosticSeverity.Error) ) { return; }

        CodeWriter code = new();
        code.Line($"// <auto-generated/> Jakar.Json.Generator {JsonGenerator.VERSION}");
        code.Line("#nullable enable annotations");
        code.Line("#pragma warning disable CS1591, CS0108, CS0114, CS0612, CS0618, CS8826");
        code.Line();

        if ( model.Namespace is not null )
        {
            code.Line($"namespace {model.Namespace};");
            code.Line();
        }

        foreach ( TypeDeclInfo container in model.ContainingTypes ) { code.Open(container.Declaration); }

        code.Open($"{model.Self.Declaration} : {J}IJsonSerializable<{model.FullyQualifiedName}>");

        EmitNames(code, model, members);
        EmitWrite(code, model, type, members, extension);
        EmitRead(code, model, type, members, extension);
        EmitMatchers(code, model, type, members);
        EmitAccessors(code, model, members);
        EmitOptions(code, model, type);
        EmitInterfaces(code, model);
        EmitHelpers(code, model);

        if ( type.GenerateToString != Values.OFF && !model.OverridesToString ) { code.Line($"public override string ToString() => {J}JsonCodec.ToJson(this);"); }

        code.Close();

        foreach ( TypeDeclInfo _ in model.ContainingTypes ) { code.Close(); }

        spc.AddSource(model.HintName, SourceText.From(code.ToString(), Encoding.UTF8));
    }


    // ─── Resolution ──────────────────────────────────────────────────────────

    private static List<Resolved> Resolve( ModelInfo model, Settings type, out MemberInfo? extension, out List<DiagnosticInfo> problems )
    {
        problems  = [];
        extension = null;

        HashSet<string> bound    = new(model.Construction.Parameters.Where(static p => p.Member is not null && !p.HasDefault).Select(static p => p.Member!), StringComparer.Ordinal);
        HashSet<string> boundAny = new(model.Construction.Parameters.Where(static p => p.Member is not null).Select(static p => p.Member!), StringComparer.Ordinal);

        // Order (SPEC.md §5.2): Order, then base members first, then declaration (file path, position).
        IEnumerable<MemberInfo> ordered = model.Members.OrderBy(static m => m.Order).ThenBy(static m => m.BaseDepth).ThenBy(static m => m.FilePath, StringComparer.Ordinal).ThenBy(static m => m.Position);

        List<Resolved> members = [];

        foreach ( MemberInfo member in ordered )
        {
            Settings settings = type.With(member.Settings);

            if ( member.IsExtensionData )
            {
                extension = member;
                continue;
            }

            string jsonName  = member.JsonNameOverride ?? Naming.Apply(member.Name, settings.Naming);
            string converter = member.Converter        ?? Converter(member.Shape, settings);
            bool   required  = member.IsRequiredKeyword || member.RequiredAttribute || bound.Contains(member.Name);

            if ( required && settings.NullValues == Values.NULLS_OMIT && member.Shape.IsNullable ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.Contradictory, member.Location ?? model.AttributeLocation, $"Member '{member.Name}' is required but NullValues = Omit can leave it out of the JSON; reading it back would fail")); }

            Determinism(model, member, settings, problems);
            members.Add(new Resolved(member, members.Count, settings, jsonName, converter, required, boundAny.Contains(member.Name), $"__m{members.Count}"));
        }

        if ( type.UnknownMembers == Values.UNKNOWN_CAPTURE && extension is null ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.Contradictory, model.AttributeLocation, $"'{model.Name}' sets UnknownMembers = Capture but has no [JsonMember(ExtensionData = true)] member to capture them in")); }

        if ( extension is not null && model.Settings.UnknownMembers == Values.UNKNOWN_ERROR ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.Contradictory, extension.Location ?? model.AttributeLocation, $"'{model.Name}' has an extension data member but UnknownMembers = Error rejects the members it would capture")); }

        // JJSON005: names must be unique (case-insensitively when matched that way); the discriminator is a name too.
        bool ignoreCase = type.NameMatching == Values.MATCHING_IGNORE_CASE;

        StringComparer comparer = ignoreCase
                                      ? StringComparer.OrdinalIgnoreCase
                                      : StringComparer.Ordinal;

        Dictionary<string, string> taken = new(comparer);
        if ( model.OwnTag is { } tag ) { taken[tag.TypeName] = "the discriminator"; }

        if ( model.Derived.Count > 0 && !taken.ContainsKey(model.Discriminator) ) { taken[model.Discriminator] = "the discriminator"; }

        foreach ( Resolved member in members )
        {
            if ( taken.TryGetValue(member.JsonName, out string? other) )
            {
                problems.Add(DiagnosticInfo.Create(JsonDiagnostics.NameCollision,
                                                   member.Member.Location ?? model.AttributeLocation,
                                                   other,
                                                   member.Name,
                                                   member.JsonName,
                                                   ignoreCase
                                                       ? " (names are matched ignoring case)"
                                                       : ""));

                continue;
            }

            taken[member.JsonName] = member.Name;
        }

        return members;
    }

    private static void Determinism( ModelInfo model, MemberInfo member, Settings settings, List<DiagnosticInfo> problems )
    {
        LocationInfo? location = member.Location ?? model.AttributeLocation;

        if ( Uses(member.Shape, ShapeKind.DateTime) && settings.LocalDateTimes == Values.LOCAL_WRITE_OFFSET ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.DeterminismWeakened, location, $"Member '{member.Name}': LocalDateTimes = WriteOffset writes local DateTime values with this machine's offset, so the JSON depends on the time zone")); }

        if ( !IsUnordered(member.Shape, out bool comparable) ) { return; }

        if ( settings.UnorderedCollections == Values.ORDER_ENUMERATION ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.DeterminismWeakened, location, $"Member '{member.Name}': UnorderedCollections = Enumeration writes it in hash order, which can differ between equal collections")); }
        else if ( !comparable ) { problems.Add(DiagnosticInfo.Create(JsonDiagnostics.DeterminismWeakened,                                          location, $"Member '{member.Name}': its elements (or keys) don't implement IComparable<T>, so it can't be written sorted and is written in hash order")); }
    }

    private static bool Uses( TypeShape shape, ShapeKind kind ) => shape.Kind == kind || shape.Element is not null && Uses(shape.Element, kind);

    private static bool IsUnordered( TypeShape shape, out bool comparable )
    {
        switch ( shape.Kind )
        {
            case ShapeKind.HashSet or ShapeKind.FrozenSet:
                comparable = shape.Element!.IsComparable;
                return true;

            case ShapeKind.Dictionary:
            case ShapeKind.Map when shape.MapKind is MapKind.Immutable or MapKind.Frozen or MapKind.Concurrent:
                comparable = shape.Key!.IsComparable;
                return true;

            case ShapeKind.Nullable:
                return IsUnordered(shape.Element!, out comparable);

            default:
                comparable = true;
                return false;
        }
    }


    // ─── Converters ──────────────────────────────────────────────────────────

    /// <summary> The type argument for a shape: reference types carry their <c>?</c>. </summary>
    private static string Arg( TypeShape shape ) => shape.IsReferenceType && shape.IsNullable
                                                        ? shape.TypeName + "?"
                                                        : shape.TypeName;

    public static string Converter( TypeShape shape, in Settings settings )
    {
        if ( shape.Kind == ShapeKind.Nullable ) { return $"{C}JsonNullableConverter<{shape.Element!.TypeName}, {Converter(shape.Element, settings)}>"; }

        if ( shape is { Kind: ShapeKind.Node, TypeName: "global::Jakar.Json.JNode" } ) { return $"{C}JsonNodeConverter"; } // null ↔ null either way

        string plain = NonNullConverter(shape, settings);

        return shape is { IsReferenceType: true, IsNullable: true }
                   ? $"{C}JsonNullableReferenceConverter<{shape.TypeName}, {plain}>"
                   : plain;
    }

    private static string NonNullConverter( TypeShape shape, in Settings settings )
    {
        string name = shape.TypeName;

        switch ( shape.Kind )
        {
            case ShapeKind.Bool:
                return $"{C}JsonBooleanConverter";

            case ShapeKind.String:
                return $"{C}JsonStringConverter";

            case ShapeKind.Char:
                return $"{C}JsonCharConverter";

            case ShapeKind.Integer:
                return $"{C}JsonIntegerConverter<{name}, {C}JsonNumberModes.Flags{IntegerMode(settings)}>";

            case ShapeKind.Float:
                return $"{C}JsonFloatConverter<{name}, {C}JsonNumberModes.Flags{FloatMode(settings)}>";

            case ShapeKind.Guid:
                return $"{C}JsonGuidConverter";

            case ShapeKind.DateTime:
                return $"{C}JsonDateTimeConverter<{C}JsonDateTimeModes.{DateTimeMode(settings)}>";

            case ShapeKind.DateTimeOffset:
                return $"{C}JsonDateTimeOffsetConverter";

            case ShapeKind.DateOnly:
                return $"{C}JsonDateOnlyConverter";

            case ShapeKind.TimeOnly:
                return $"{C}JsonTimeOnlyConverter";

            case ShapeKind.TimeSpan:
                return $"{C}JsonTimeSpanConverter";

            case ShapeKind.Uri:
                return $"{C}JsonUriConverter";

            case ShapeKind.Version:
                return $"{C}JsonVersionConverter";

            case ShapeKind.Parsable:
                return $"{C}JsonParsableConverter<{name}>";

            case ShapeKind.Model:
                return $"{C}JsonModelConverter<{name}>";

            case ShapeKind.Node:
                return $"{C}JsonNodeConverter<{name}>";

            case ShapeKind.Enum:
                return settings.Enums == Values.ENUMS_NUMBER
                           ? $"{C}JsonEnumNumberConverter<{name}, {shape.Enum!.UnderlyingType}>"
                           : TypeShapes.WithNaming(shape.Enum!, settings.EnumNaming).ConverterName;
        }

        TypeShape element = shape.Element!;
        string    e       = Arg(element);
        string    ec      = Converter(element, settings);

        switch ( shape.Kind )
        {
            case ShapeKind.Array:
                return $"{C}JsonArrayConverter<{e}, {ec}>";

            case ShapeKind.List:
                return $"{C}JsonListConverter<{e}, {ec}>";

            case ShapeKind.Enumerable:
                return $"{C}JsonEnumerableConverter<{name}, {e}, {ec}>";

            case ShapeKind.ImmutableArray:
                return $"{C}JsonImmutableArrayConverter<{e}, {ec}>";

            case ShapeKind.ImmutableList:
                return $"{C}JsonImmutableListConverter<{e}, {ec}>";

            case ShapeKind.HashSet:
                return $"{C}JsonHashSetConverter<{name}, {e}, {ec}, {Order(settings, element)}>";

            case ShapeKind.FrozenSet:
                return $"{C}JsonFrozenSetConverter<{e}, {ec}, {Order(settings, element)}>";

            case ShapeKind.SortedSet:
                return $"{C}JsonSortedSetConverter<{e}, {ec}>";

            case ShapeKind.Queue:
                return $"{C}JsonQueueConverter<{e}, {ec}>";

            case ShapeKind.Stack:
                return $"{C}JsonStackConverter<{e}, {ec}>";
        }

        TypeShape key = shape.Key!;
        string    k   = key.TypeName;
        string    kc  = KeyConverter(key, settings);

        if ( shape.Kind == ShapeKind.Dictionary ) { return $"{C}JsonDictionaryConverter<{name}, {k}, {e}, {kc}, {ec}, {Order(settings, key)}>"; }

        string order = shape.MapKind is MapKind.Immutable or MapKind.Frozen or MapKind.Concurrent
                           ? Order(settings, key)
                           : $"{C}JsonOrders.Enumeration<{k}>"; // sorted and ordered maps have their own order

        string factory = shape.MapKind switch
                         {
                             MapKind.Sorted          => "Sorted",
                             MapKind.Ordered         => "Ordered",
                             MapKind.Immutable       => "Immutable",
                             MapKind.ImmutableSorted => "ImmutableSorted",
                             MapKind.Frozen          => "Frozen",
                             _                       => "Concurrent"
                         };

        return $"{C}JsonMapConverter<{name}, {k}, {e}, {kc}, {ec}, {order}, {C}JsonMapFactories.{factory}<{k}, {e}>>";
    }

    private static string KeyConverter( TypeShape key, in Settings settings ) => key.Kind switch
                                                                                 {
                                                                                     ShapeKind.String => $"{C}JsonStringKeyConverter",
                                                                                     ShapeKind.Enum   => TypeShapes.WithNaming(key.Enum!, settings.EnumNaming).ConverterName,
                                                                                     _                => $"{C}JsonParsableKeyConverter<{key.TypeName}>"
                                                                                 };

    /// <summary> The order for an unordered collection's elements or keys: a compile-time comparison, or enumeration order. </summary>
    private static string Order( in Settings settings, TypeShape item )
    {
        string arg = Arg(item);
        if ( settings.UnorderedCollections == Values.ORDER_ENUMERATION || !item.IsComparable ) { return $"{C}JsonOrders.Enumeration<{arg}>"; }

        return item.Kind switch
               {
                   ShapeKind.String   => $"{C}JsonOrders.Ordinal",
                   ShapeKind.Enum     => $"{C}JsonOrders.Enum<{item.TypeName}, {item.Enum!.UnderlyingType}>",
                   ShapeKind.Nullable => $"{C}JsonOrders.Nullable<{item.Element!.TypeName}, {Order(settings, item.Element)}>",
                   _                  => $"{C}JsonOrders.Comparable<{arg}>"
               };
    }

    private static int IntegerMode( in Settings settings ) => ( settings.NumbersFromStrings == Values.NUMBERS_ALLOW_STRINGS
                                                                    ? 1
                                                                    : 0 ) |
                                                              ( settings.LargeIntegers == Values.LARGE_AS_STRING
                                                                    ? 2
                                                                    : 0 );

    private static int FloatMode( in Settings settings ) => ( settings.NumbersFromStrings == Values.NUMBERS_ALLOW_STRINGS
                                                                  ? 1
                                                                  : 0 ) |
                                                            ( settings.NonFiniteFloats == Values.NON_FINITE_AS_STRING
                                                                  ? 4
                                                                  : 0 );

    private static string DateTimeMode( in Settings settings ) => settings.LocalDateTimes switch
                                                                  {
                                                                      Values.LOCAL_WRITE_OFFSET => "WriteOffset",
                                                                      Values.LOCAL_ERROR        => "Error",
                                                                      _                         => "ConvertToUtc"
                                                                  };


    // ─── Names ───────────────────────────────────────────────────────────────

    private static void EmitNames( CodeWriter code, ModelInfo model, List<Resolved> members )
    {
        foreach ( Resolved member in members )
        {
            if ( Naming.CanPreEncode(member.JsonName) ) { code.Line($"private static {J}JsonName __JsonName{member.Index} => new({EncodedName(member.JsonName)}, {EncodedName(member.JsonName)}u8);"); }
        }

        string? discriminator = model.OwnTag?.TypeName;
        if ( discriminator is not null && Naming.CanPreEncode(discriminator) ) { code.Line($"private static {J}JsonName __JsonDiscriminator => new({EncodedName(discriminator)}, {EncodedName(discriminator)}u8);"); }

        code.Line();
    }

    /// <summary> <c>"\"name\" : "</c> as a C# literal. </summary>
    private static string EncodedName( string name ) => Naming.Literal($"\"{Naming.EscapeJson(name)}\" : ");

    private static string WriteName( Resolved member ) => Naming.CanPreEncode(member.JsonName)
                                                              ? $"writer.WritePropertyName(__JsonName{member.Index});"
                                                              : $"writer.WritePropertyName({Naming.Literal(member.JsonName)});";


    // ─── Write ───────────────────────────────────────────────────────────────

    private static void EmitWrite( CodeWriter code, ModelInfo model, Settings type, List<Resolved> members, MemberInfo? extension )
    {
        string self       = model.FullyQualifiedName;
        bool   dispatches = model.Derived.Count > 0;

        code.Line($"/// <summary> Writes <paramref name=\"value\"/> as JSON (generated by Jakar.Json). </summary>");

        using ( code.Block($"public static void WriteJson<{W}>( ref {W} writer, scoped in {self} value ) where {W} : {J}IJsonWriter, allows ref struct") )
        {
            if ( !model.IsValueType )
            {
                using ( code.Block("if ( value is null )") )
                {
                    code.Line("writer.WriteNull();");
                    code.Line("return;");
                }
            }

            if ( dispatches )
            {
                using ( code.Block("switch ( value )") )
                {
                    for ( int i = 0; i < model.Derived.Count; i++ )
                    {
                        DerivedInfo derived = model.Derived[i];
                        code.Line($"case {derived.TypeName} __derived{i}: {derived.TypeName}.WriteJson(ref writer, in __derived{i}); return;");
                    }
                }

                if ( model.IsAbstract ) { code.Line($"throw new {J}JsonWriteException(new {J}JsonError({J}JsonErrorKind.UnknownDiscriminator, 0, 0, 0), \"The value's type isn't listed in a [JsonDerived] on '{model.Name}'.\");"); }
                else { code.Line("WriteJsonCore(ref writer, in value);"); }
            }
            else { EmitWriteBody(code, model, type, members, extension); }
        }

        code.Line();

        if ( dispatches && !model.IsAbstract )
        {
            using ( code.Block($"private static void WriteJsonCore<{W}>( ref {W} writer, scoped in {self} value ) where {W} : {J}IJsonWriter, allows ref struct") ) { EmitWriteBody(code, model, type, members, extension); }

            code.Line();
        }
    }

    private static void EmitWriteBody( CodeWriter code, ModelInfo model, Settings type, List<Resolved> members, MemberInfo? extension )
    {
        code.Line("writer.WriteStartObject();");

        if ( model.OwnTag is { } tag )
        {
            code.Line(Naming.CanPreEncode(tag.TypeName)
                          ? "writer.WritePropertyName(__JsonDiscriminator);"
                          : $"writer.WritePropertyName({Naming.Literal(tag.TypeName)});");

            code.Line($"writer.WriteString({Naming.Literal(tag.Tag)});");
        }

        foreach ( Resolved member in members )
        {
            if ( !member.Member.CanGet ) { continue; }

            string value = $"value.{Id(member.Name)}";
            string write = $"{WriteName(member)} {member.Converter}.Write(ref writer, {value});";

            string? condition = null;

            if ( member.Settings.DefaultValues == Values.DEFAULTS_OMIT )
            {
                condition = member.Member.Shape.IsReferenceType
                                ? $"{value} is not null"
                                : $"!global::System.Collections.Generic.EqualityComparer<{member.Member.TypeName}>.Default.Equals({value}, default!)";
            }
            else if ( member.Settings.NullValues == Values.NULLS_OMIT && member.Member.Shape.IsNullable ) { condition = $"{value} is not null"; }

            code.Line(condition is null
                          ? write
                          : $"if ( {condition} ) {{ {write} }}");
        }

        if ( extension is not null )
        {
            using ( code.Block($"if ( value.{Id(extension.Name)} is {{ }} __extension )") )
            {
                using ( code.Block("foreach ( global::System.Collections.Generic.KeyValuePair<string, global::Jakar.Json.JNode?> __pair in __extension )") )
                {
                    code.Line("writer.WritePropertyName(__pair.Key);");
                    code.Line($"{J}JNode.Write(__pair.Value, ref writer);");
                }
            }
        }

        code.Line("writer.WriteEndObject();");
    }


    // ─── Read ────────────────────────────────────────────────────────────────

    private static void EmitRead( CodeWriter code, ModelInfo model, Settings type, List<Resolved> members, MemberInfo? extension )
    {
        string self = model.FullyQualifiedName;

        code.Line("/// <summary> Reads a value written by <see cref=\"WriteJson\"/>; <see langword=\"false\"/> (with <c>reader.Error</c>) on malformed or mismatched JSON (generated by Jakar.Json). </summary>");

        using ( code.Block($"public static bool TryReadJson<{R}>( ref {R} reader, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} value ) where {R} : {J}IJsonReader, allows ref struct") )
        {
            if ( model.Derived.Count > 0 )
            {
                EmitDispatch(code, model);

                code.Line(model.IsAbstract
                              ? $"return reader.Fail({J}JsonErrorKind.UnknownDiscriminator);"
                              : "return TryReadJsonCore(ref reader, out value);");
            }
            else { EmitReadBody(code, model, type, members, extension); }
        }

        code.Line();

        if ( model.Derived.Count > 0 && !model.IsAbstract )
        {
            using ( code.Block($"private static bool TryReadJsonCore<{R}>( ref {R} reader, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} value ) where {R} : {J}IJsonReader, allows ref struct") ) { EmitReadBody(code, model, type, members, extension); }

            code.Line();
        }
    }

    /// <summary> Finds the discriminator (looking ahead, then rewinding) and hands the object to the derived type that owns the tag. </summary>
    private static void EmitDispatch( CodeWriter code, ModelInfo model )
    {
        code.Line("value = default;");
        code.Line($"{J}JsonReaderCheckpoint __start = reader.Checkpoint();");
        code.Line("int __tag = -1;");
        code.Line("if ( !reader.TryReadStartObject() ) { return false; }");

        using ( code.Block("while ( true )") )
        {
            code.Line($"if ( !reader.TryReadProperty(out {J}JsonSpan __name, out bool __end) ) {{ return false; }}");
            code.Line("if ( __end ) { break; }");

            using ( code.Block($"if ( __name.Equals({Naming.Literal(model.Discriminator)}) )") )
            {
                code.Line($"if ( !reader.TryReadStringSpan(out {J}JsonSpan __tagText) ) {{ return false; }}");
                code.Line("__tag = -2;");

                for ( int i = 0; i < model.Derived.Count; i++ ) { code.Line($"if ( __tagText.Equals({Naming.Literal(model.Derived[i].Tag)}) ) {{ __tag = {i}; }}"); }

                code.Line("break;");
            }

            code.Line("if ( !reader.TrySkipValue() ) { return false; }");
        }

        code.Line("reader.Rewind(in __start);");

        using ( code.Block("switch ( __tag )") )
        {
            for ( int i = 0; i < model.Derived.Count; i++ )
            {
                string derived = model.Derived[i].TypeName;
                code.Line($"case {i}: {{ if ( !{derived}.TryReadJson(ref reader, out {derived}? __derived) ) {{ return false; }} value = __derived; return true; }}");
            }

            code.Line($"case -2: return reader.Fail({J}JsonErrorKind.UnknownDiscriminator);");
        }
    }

    private static void EmitReadBody( CodeWriter code, ModelInfo model, Settings type, List<Resolved> members, MemberInfo? extension )
    {
        int  words      = Math.Max(1, ( members.Count + 63 ) / 64);
        bool duplicates = type.DuplicateMembers != Values.DUPLICATES_LAST_WINS;

        int unknown = extension is not null && model.Settings.UnknownMembers != Values.UNKNOWN_ERROR
                          ? Values.UNKNOWN_CAPTURE
                          : type.UnknownMembers;

        code.Line("value = default;");
        code.Line("if ( !reader.TryReadStartObject() ) { return false; }");

        Dictionary<string, string> defaults = model.Construction.Parameters.Where(static p => p.Member is not null && p.HasDefault).ToDictionary(static p => p.Member!, static p => p.DefaultLiteral!, StringComparer.Ordinal);

        foreach ( Resolved member in members ) { code.Line($"{member.Member.TypeName} {member.Local} = {( defaults.TryGetValue(member.Name, out string? literal) ? literal : "default!" )};"); }

        for ( int word = 0; word < words; word++ ) { code.Line($"ulong __seen{word} = 0;"); }

        if ( extension is not null ) { code.Line($"{extension.TypeName.TrimEnd('?')}? __extension = null;"); }

        using ( code.Block("while ( true )") )
        {
            code.Line($"if ( !reader.TryReadProperty(out {J}JsonSpan __name, out bool __end) ) {{ return false; }}");
            code.Line("if ( __end ) { break; }");

            using ( code.Block("switch ( __name.IsUtf8 ? __JsonMatch(__name.Utf8) : __JsonMatch(__name.Utf16) )") )
            {
                foreach ( Resolved member in members )
                {
                    string bit  = $"__seen{member.Index / 64}";
                    string mask = $"{1UL << ( member.Index % 64 )}UL";

                    using ( code.Block($"case {member.Index}:") )
                    {
                        if ( duplicates ) { code.Line($"if ( ( {bit} & {mask} ) != 0 ) {{ return reader.Fail({J}JsonErrorKind.DuplicateMember); }}"); }

                        code.Line($"if ( !{member.Converter}.TryRead(ref reader, out {member.Local}) ) {{ return false; }}");
                        code.Line($"{bit} |= {mask};");
                        code.Line("break;");
                    }
                }

                if ( model.OwnTag is { } tag )
                {
                    using ( code.Block("case -2:") ) // the discriminator, written by WriteJson: it must name this type
                    {
                        code.Line($"if ( !reader.TryReadStringSpan(out {J}JsonSpan __tagText) ) {{ return false; }}");
                        code.Line($"if ( !__tagText.Equals({Naming.Literal(tag.Tag)}) ) {{ return reader.Fail({J}JsonErrorKind.UnknownDiscriminator); }}");
                        code.Line("break;");
                    }
                }

                using ( code.Block("default:") )
                {
                    switch ( unknown )
                    {
                        case Values.UNKNOWN_ERROR:
                            code.Line($"return reader.Fail({J}JsonErrorKind.UnknownMember);");
                            break;

                        case Values.UNKNOWN_CAPTURE:
                            code.Line("string __key = __name.ToString();");
                            code.Line($"if ( !{J}JNode.TryRead(ref reader, out {J}JNode? __captured) ) {{ return false; }}");
                            code.Line($"( __extension ??= new() )[__key] = __captured;");
                            code.Line("break;");
                            break;

                        default:
                            code.Line("if ( !reader.TrySkipValue() ) { return false; }");
                            code.Line("break;");
                            break;
                    }
                }
            }
        }

        // Required members: one mask per 64 members.
        for ( int word = 0; word < words; word++ )
        {
            ulong required = 0;

            foreach ( Resolved member in members.Where(m => m.Required && m.Index / 64 == word) ) { required |= 1UL << ( member.Index % 64 ); }

            if ( required != 0 ) { code.Line($"if ( ( __seen{word} & {required}UL ) != {required}UL ) {{ return reader.Fail({J}JsonErrorKind.MissingRequired); }}"); }
        }

        EmitConstruction(code, model, members, extension);
        code.Line("return true;");
    }

    private static void EmitConstruction( CodeWriter code, ModelInfo model, List<Resolved> members, MemberInfo? extension )
    {
        ConstructionInfo construction = model.Construction;

        if ( construction.Kind == ConstructionKind.None )
        {
            code.Line($"return reader.Fail({J}JsonErrorKind.UnknownDiscriminator);");
            return;
        }

        Dictionary<string, Resolved> byName = members.ToDictionary(static m => m.Name, StringComparer.Ordinal);

        string arguments = string.Join(", ",
                                       construction.Parameters.Select(p => p.Member is not null && byName.TryGetValue(p.Member, out Resolved? member)
                                                                               ? member.Local
                                                                               : p.DefaultLiteral ?? "default!"));

        // `required` members go in the initializer (the compiler insists, and they're always present: a missing one failed above).
        List<string> initializers = [];

        if ( !construction.SetsRequiredMembers )
        {
            foreach ( Resolved member in members.Where(static m => m.Member.IsRequiredKeyword && !m.Bound) ) { initializers.Add($"{Id(member.Name)} = {member.Local}"); }
        }

        string initializer = initializers.Count == 0
                                 ? ""
                                 : $" {{ {string.Join(", ", initializers)} }}";

        code.Line($"value = new {model.FullyQualifiedName}({arguments}){initializer};");

        // Everything else is assigned only when present, so property initializers survive a missing member.
        foreach ( Resolved member in members )
        {
            if ( member.Bound || member.Member.IsRequiredKeyword && !construction.SetsRequiredMembers ) { continue; }

            string present = $"( __seen{member.Index / 64} & {1UL << ( member.Index % 64 )}UL ) != 0";

            switch ( member.Member.Setter )
            {
                case SetterKind.Set or SetterKind.Field:
                    code.Line($"if ( {present} ) {{ value.{Id(member.Name)} = {member.Local}; }}");
                    break;

                case SetterKind.Init:
                    code.Line($"if ( {present} ) {{ __JsonInit{member.Index}({( member.Member.DeclaringIsValueType ? "ref " : "" )}value, {member.Local}); }}");
                    break;
            }
        }

        if ( extension is not null && extension.Setter is not (SetterKind.None or SetterKind.ReadOnlyField) )
        {
            code.Line(extension.Setter == SetterKind.Init
                          ? $"if ( __extension is not null ) {{ __JsonInitExtension({( extension.DeclaringIsValueType ? "ref " : "" )}value, __extension); }}"
                          : $"if ( __extension is not null ) {{ value.{Id(extension.Name)} = __extension; }}");
        }
    }


    // ─── Name matching ───────────────────────────────────────────────────────

    /// <summary> <c>__JsonMatch</c>: name → member index (−1 unknown, −2 the discriminator), for UTF-16 and UTF-8. A switch on length, then ordinal comparisons against constants. </summary>
    private static void EmitMatchers( CodeWriter code, ModelInfo model, Settings type, List<Resolved> members )
    {
        bool ignoreCase = type.NameMatching == Values.MATCHING_IGNORE_CASE;

        List<(string Name, int Index)> names = members.Select(static m => ( m.JsonName, m.Index )).ToList();
        if ( model.OwnTag is { } tag ) { names.Add(( tag.TypeName, -2 )); }

        // UTF-16
        using ( code.Block("private static int __JsonMatch( global::System.ReadOnlySpan<char> name )") )
        {
            if ( names.Count == 0 ) { code.Line("return -1;"); }
            else
            {
                using ( code.Block("switch ( name.Length )") )
                {
                    foreach ( IGrouping<int, (string Name, int Index)> group in names.GroupBy(static n => n.Name.Length).OrderBy(static g => g.Key) )
                    {
                        using ( code.Block($"case {group.Key}:") )
                        {
                            foreach ( ( string name, int index ) in group )
                            {
                                string compare = ignoreCase
                                                     ? $"global::System.MemoryExtensions.Equals(name, {Naming.Literal(name)}, global::System.StringComparison.OrdinalIgnoreCase)"
                                                     : $"global::System.MemoryExtensions.SequenceEqual(name, {Naming.Literal(name)})";

                                code.Line($"if ( {compare} ) {{ return {index}; }}");
                            }

                            code.Line("return -1;");
                        }
                    }
                }

                code.Line("return -1;");
            }
        }

        code.Line();

        // UTF-8
        using ( code.Block("private static int __JsonMatch( global::System.ReadOnlySpan<byte> name )") )
        {
            if ( names.Count == 0 ) { code.Line("return -1;"); }
            else if ( ignoreCase && !names.All(static n => Naming.IsAscii(n.Name)) )
            {
                // Non-ASCII names compared ignoring case: decode, then match as UTF-16.
                code.Line("global::System.Span<char> __chars = name.Length <= 256 ? stackalloc char[256] : new char[name.Length];");
                code.Line("return global::System.Text.Unicode.Utf8.ToUtf16(name, __chars, out _, out int __written) == global::System.Buffers.OperationStatus.Done ? __JsonMatch(__chars[..__written]) : -1;");
            }
            else
            {
                using ( code.Block("switch ( name.Length )") )
                {
                    foreach ( IGrouping<int, (string Name, int Index)> group in names.GroupBy(static n => Naming.Utf8Length(n.Name)).OrderBy(static g => g.Key) )
                    {
                        using ( code.Block($"case {group.Key}:") )
                        {
                            foreach ( ( string name, int index ) in group )
                            {
                                string compare = ignoreCase
                                                     ? $"global::System.Text.Ascii.EqualsIgnoreCase(name, {Naming.Literal(name)}u8)"
                                                     : $"global::System.MemoryExtensions.SequenceEqual(name, {Naming.Literal(name)}u8)";

                                code.Line($"if ( {compare} ) {{ return {index}; }}");
                            }

                            code.Line("return -1;");
                        }
                    }
                }

                code.Line("return -1;");
            }
        }

        code.Line();
    }


    // ─── Init-only setters ───────────────────────────────────────────────────

    /// <summary> Init-only members are set only when present (so their initializers survive), outside an object initializer: through <c>[UnsafeAccessor]</c>, which binds at compile time (no reflection). </summary>
    private static void EmitAccessors( CodeWriter code, ModelInfo model, List<Resolved> members )
    {
        foreach ( Resolved member in members )
        {
            if ( member.Member.Setter != SetterKind.Init || member.Bound || member.Member.IsRequiredKeyword && !model.Construction.SetsRequiredMembers ) { continue; }

            EmitAccessor(code, $"__JsonInit{member.Index}", member.Member);
        }

        MemberInfo? extension = model.Members.FirstOrDefault(static m => m.IsExtensionData);
        if ( extension is { Setter: SetterKind.Init } ) { EmitAccessor(code, "__JsonInitExtension", extension); }
    }

    private static void EmitAccessor( CodeWriter code, string name, MemberInfo member )
    {
        string target = member.DeclaringIsValueType
                            ? $"ref {member.DeclaringType}"
                            : member.DeclaringType;

        code.Line($"[global::System.Runtime.CompilerServices.UnsafeAccessor(global::System.Runtime.CompilerServices.UnsafeAccessorKind.Method, Name = \"set_{member.Name}\")]");
        code.Line($"private static extern void {name}( {target} target, {member.TypeName} value );");
        code.Line();
    }


    // ─── Options ─────────────────────────────────────────────────────────────

    private static void EmitOptions( CodeWriter code, ModelInfo model, Settings type )
    {
        string modifier = model.HasSerializableBase
                              ? "new "
                              : "";

        if ( !model.Skip.Contains("DefaultWriterOptions") ) { code.Line($"public static {modifier}{J}JsonWriterOptions DefaultWriterOptions => new() {{ Indented = {Bool(type.Indented == Values.ON)}, IndentChar = ({J}JsonIndentChar){type.IndentChar}, IndentSize = {type.IndentSize}, Escaping = ({J}JsonEscaping){type.Escaping}, MaxDepth = {type.MaxDepth} }};"); }

        if ( !model.Skip.Contains("DefaultReaderOptions") ) { code.Line($"public static {modifier}{J}JsonReaderOptions DefaultReaderOptions => new() {{ AllowComments = {Bool(type.AllowComments == Values.ON)}, AllowTrailingCommas = {Bool(type.AllowTrailingCommas == Values.ON)}, MaxDepth = {type.MaxDepth} }};"); }

        code.Line();
    }


    // ─── ISpanFormattable / ISpanParsable (and UTF-8) ────────────────────────

    private static void EmitInterfaces( CodeWriter code, ModelInfo model )
    {
        string self = model.FullyQualifiedName;

        string @new = model.HasSerializableBase
                          ? "new "
                          : "";

        void Emit( string key, string member )
        {
            if ( !model.Skip.Contains(key) ) { code.Line(member); }
        }

        Emit("TryFormat:chars", $"public {@new}bool TryFormat( global::System.Span<char> destination, out int charsWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider ) => {J}JsonCodec.TryFormat(this, destination, out charsWritten, format);");
        Emit("TryFormat:bytes", $"public {@new}bool TryFormat( global::System.Span<byte> utf8Destination, out int bytesWritten, global::System.ReadOnlySpan<char> format, global::System.IFormatProvider? provider ) => {J}JsonCodec.TryFormat(this, utf8Destination, out bytesWritten, format);");
        Emit("ToString:format", $"public {@new}string ToString( string? format, global::System.IFormatProvider? formatProvider ) => {J}JsonCodec.ToJson(this, global::System.MemoryExtensions.AsSpan(format));");
        Emit("Parse:chars",     $"public static {@new}{self} Parse( global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider ) => {J}JsonCodec.FromJson<{self}>(s);");
        Emit("TryParse:chars",  $"public static bool TryParse( global::System.ReadOnlySpan<char> s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} result ) => {J}JsonCodec.TryFromJson(s, out result);");
        Emit("Parse:string",    $"public static {@new}{self} Parse( string s, global::System.IFormatProvider? provider ) => {J}JsonCodec.FromJson<{self}>(s);");
        Emit("TryParse:string", $"public static bool TryParse( [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} result ) => {J}JsonCodec.TryFromJson(s, out result);");
        Emit("Parse:bytes",     $"public static {@new}{self} Parse( global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider ) => {J}JsonCodec.FromJson<{self}>(utf8Text);");
        Emit("TryParse:bytes",  $"public static bool TryParse( global::System.ReadOnlySpan<byte> utf8Text, global::System.IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} result ) => {J}JsonCodec.TryFromJson(utf8Text, out result);");
        code.Line();
    }


    // ─── Helpers ─────────────────────────────────────────────────────────────

    private static void EmitHelpers( CodeWriter code, ModelInfo model )
    {
        string self = model.FullyQualifiedName;

        string @new = model.HasSerializableBase
                          ? "new "
                          : "";

        string options = $"{J}JsonWriterOptions? options = null";
        string read    = $"{J}JsonReaderOptions? options = null";

        void Emit( string key, string member )
        {
            if ( !model.Skip.Contains(key) ) { code.Line(member); }
        }

        Emit("ToJson",             $"public {@new}string ToJson( {options} ) => {J}JsonCodec.ToJson(this, options);");
        Emit("ToJsonUtf8",         $"public {@new}byte[] ToJsonUtf8( {options} ) => {J}JsonCodec.ToJsonUtf8(this, options);");
        Emit("ToJson:stream",      $"public {@new}void ToJson( global::System.IO.Stream stream, {options} ) => {J}JsonCodec.ToJson(this, stream, options);");
        Emit("ToJsonAsync",        $"public {@new}global::System.Threading.Tasks.ValueTask ToJsonAsync( global::System.IO.Stream stream, {options}, global::System.Threading.CancellationToken token = default ) => {J}JsonCodec.ToJsonAsync(this, stream, options, token);");
        Emit("WriteJson:buffer",   $"public {@new}void WriteJson( global::System.Buffers.IBufferWriter<byte> output, {options} ) => {J}JsonCodec.WriteJson(this, output, options);");
        Emit("FromJson:string",    $"public static {@new}{self} FromJson( string json, {read} ) => {J}JsonCodec.FromJson<{self}>(json, options);");
        Emit("FromJson:chars",     $"public static {@new}{self} FromJson( global::System.ReadOnlySpan<char> json, {read} ) => {J}JsonCodec.FromJson<{self}>(json, options);");
        Emit("FromJson:bytes",     $"public static {@new}{self} FromJson( global::System.ReadOnlySpan<byte> utf8Json, {read} ) => {J}JsonCodec.FromJson<{self}>(utf8Json, options);");
        Emit("FromJson:stream",    $"public static {@new}{self} FromJson( global::System.IO.Stream utf8Json, {read} ) => {J}JsonCodec.FromJson<{self}>(utf8Json, options);");
        Emit("FromJsonAsync",      $"public static {@new}global::System.Threading.Tasks.ValueTask<{self}> FromJsonAsync( global::System.IO.Stream utf8Json, {read}, global::System.Threading.CancellationToken token = default ) => {J}JsonCodec.FromJsonAsync<{self}>(utf8Json, options, token);");
        Emit("TryFromJson:string", $"public static bool TryFromJson( [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? json, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} value, {read} ) => {J}JsonCodec.TryFromJson(json, out value, options);");
        Emit("TryFromJson:chars",  $"public static bool TryFromJson( global::System.ReadOnlySpan<char> json, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} value, {read} ) => {J}JsonCodec.TryFromJson(json, out value, options);");
        Emit("TryFromJson:bytes",  $"public static bool TryFromJson( global::System.ReadOnlySpan<byte> utf8Json, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {self} value, {read} ) => {J}JsonCodec.TryFromJson(utf8Json, out value, options);");
        code.Line();
    }


    // ─── Small helpers ───────────────────────────────────────────────────────

    private static string Bool( bool value ) => value
                                                    ? "true"
                                                    : "false";

    /// <summary> A member name as an identifier (<c>@class</c> for keywords). </summary>
    public static string Id( string name ) => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None
                                                  ? "@" + name
                                                  : name;

    public static string Number( ulong value ) => value.ToString(CultureInfo.InvariantCulture);
}
