// Jakar.Json.Generator
// 10/07/2026

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;



namespace Jakar.Json.Generator;


/// <summary>
///     One converter struct per (enum, naming policy) used in the assembly: names by <c>switch</c> (never <c>Enum.ToString</c>, no reflection), <c>[Flags]</c> values as
///     <c>"A, B"</c> in ascending bit order, values without a name as numbers. Reading accepts the names or a number. Also the enum's dictionary-key converter.
/// </summary>
internal static class EnumEmitter
{
    private const string J = "global::Jakar.Json.";


    public static void Emit( SourceProductionContext spc, ImmutableArray<EnumInfo> all )
    {
        List<EnumInfo> enums = all.GroupBy(static e => e.ConverterName).Select(static g => g.First()).OrderBy(static e => e.ConverterName, System.StringComparer.Ordinal).ToList();
        if ( enums.Count == 0 ) { return; }

        CodeWriter code = new();
        code.Line($"// <auto-generated/> Jakar.Json.Generator {JsonGenerator.VERSION}");
        code.Line("#nullable enable annotations");
        code.Line("#pragma warning disable CS1591, CS0612, CS0618");
        code.Line();
        code.Line("namespace Jakar.Json.Generated;");
        code.Line();

        using ( code.Block("internal static partial class JsonEnums") )
        {
            foreach ( EnumInfo info in enums ) { EmitConverter(code, info); }
        }

        spc.AddSource("Jakar.Json.Enums.g.cs", SourceText.From(code.ToString(), Encoding.UTF8));
    }


    private static void EmitConverter( CodeWriter code, EnumInfo info )
    {
        string type       = info.FullyQualifiedName;
        string underlying = info.UnderlyingType;
        string name       = info.ConverterName.Substring(info.ConverterName.LastIndexOf('.') + 1);

        List<EnumMemberInfo> members = info.Members.ToList();

        using ( code.Block($"internal readonly struct {name} : {J}IJsonConverter<{type}>, {J}IJsonKeyConverter<{type}>") )
        {
            // ─── Write ───────────────────────────────────────────────────────
            using ( code.Block($"public static void Write<TWriter>( ref TWriter writer, scoped in {type} value ) where TWriter : {J}IJsonWriter, allows ref struct") )
            {
                code.Line("global::System.Span<char> __buffer = stackalloc char[256];");
                code.Line("int __length = Format(value, __buffer);");
                code.Line($"if ( __length >= 0 ) {{ writer.WriteString(__buffer[..__length]); }}");
                code.Line($"else {{ writer.WriteInteger(global::System.Runtime.CompilerServices.Unsafe.BitCast<{type}, {underlying}>(value)); }}");
            }

            code.Line();

            using ( code.Block($"public static void WriteKey<TWriter>( ref TWriter writer, {type} key ) where TWriter : {J}IJsonWriter, allows ref struct") )
            {
                code.Line("global::System.Span<char> __buffer = stackalloc char[256];");
                code.Line("int __length = Format(key, __buffer);");
                code.Line($"if ( __length < 0 ) {{ global::System.Runtime.CompilerServices.Unsafe.BitCast<{type}, {underlying}>(key).TryFormat(__buffer, out __length, default, global::System.Globalization.CultureInfo.InvariantCulture); }}");
                code.Line("writer.WritePropertyName(__buffer[..__length]);");
            }

            code.Line();

            // The name (or "A, B" for flags) into buffer; -1 when the value has no name.
            using ( code.Block($"private static int Format( {type} value, global::System.Span<char> buffer )") )
            {
                using ( code.Block("switch ( value )") )
                {
                    foreach ( EnumMemberInfo member in members ) { code.Line($"case {type}.{Emitter.Id(member.Name)}: return Copy({Naming.Literal(member.JsonName)}, buffer);"); }
                }

                if ( info.IsFlags )
                {
                    code.Line($"ulong __bits = unchecked((ulong)global::System.Runtime.CompilerServices.Unsafe.BitCast<{type}, {underlying}>(value));");
                    code.Line("int __written = 0;");

                    // Ascending bit order: deterministic, independent of declaration order.
                    foreach ( EnumMemberInfo member in members.Where(static m => m.Bits != 0).OrderBy(static m => m.Bits) )
                    {
                        string bits = $"{Emitter.Number(member.Bits)}UL";

                        using ( code.Block($"if ( ( __bits & {bits} ) == {bits} )") )
                        {
                            code.Line("if ( __written > 0 ) { if ( !Copy(\", \", buffer, ref __written) ) { return -1; } }");
                            code.Line($"if ( !Copy({Naming.Literal(member.JsonName)}, buffer, ref __written) ) {{ return -1; }}");
                            code.Line($"__bits &= ~{bits};");
                        }
                    }

                    code.Line("return __bits == 0 && __written > 0 ? __written : -1;");
                }
                else { code.Line("return -1;"); }
            }

            code.Line();
            code.Line("private static int Copy( string text, global::System.Span<char> buffer ) => global::System.MemoryExtensions.AsSpan(text).TryCopyTo(buffer) ? text.Length : -1;");

            using ( code.Block("private static bool Copy( string text, global::System.Span<char> buffer, ref int written )") )
            {
                code.Line("if ( !global::System.MemoryExtensions.AsSpan(text).TryCopyTo(buffer[written..]) ) { return false; }");
                code.Line("written += text.Length;");
                code.Line("return true;");
            }

            code.Line();

            // ─── Read ────────────────────────────────────────────────────────
            using ( code.Block($"public static bool TryRead<TReader>( ref TReader reader, out {type} value ) where TReader : {J}IJsonReader, allows ref struct") )
            {
                code.Line("value = default;");

                using ( code.Block($"if ( reader.PeekKind() == {J}JsonTokenKind.Number )") )
                {
                    code.Line($"if ( !reader.TryReadInteger(out {underlying} __number) ) {{ return false; }}");
                    code.Line($"value = global::System.Runtime.CompilerServices.Unsafe.BitCast<{underlying}, {type}>(__number);");
                    code.Line("return true;");
                }

                code.Line($"{J}JsonReaderCheckpoint __mark = reader.Checkpoint();");
                code.Line($"if ( !reader.TryReadStringSpan(out {J}JsonSpan __text) ) {{ return false; }}");
                code.Line("global::System.Span<char> __chars = stackalloc char[256];");
                code.Line("if ( __text.Length <= 256 && TryParseKey(__chars[..__text.CopyTo(__chars)], out value) ) { return true; }");
                code.Line("reader.Rewind(in __mark);");
                code.Line($"return reader.Fail({J}JsonErrorKind.InvalidValue);");
            }

            code.Line();

            // Names (or "A, B" for flags), or the number as text.
            using ( code.Block($"public static bool TryParseKey( scoped global::System.ReadOnlySpan<char> name, out {type} key )") )
            {
                code.Line("key = default;");

                if ( info.IsFlags )
                {
                    code.Line("ulong __bits = 0;");

                    using ( code.Block("while ( true )") )
                    {
                        code.Line("int __comma = global::System.MemoryExtensions.IndexOf(name, ',');");
                        code.Line("global::System.ReadOnlySpan<char> __part = global::System.MemoryExtensions.Trim(__comma < 0 ? name : name[..__comma], ' ');");
                        code.Line("if ( !TryParseOne(__part, out ulong __one) ) { return __comma < 0 && __bits == 0 && TryParseNumber(name, out key); }");
                        code.Line("__bits |= __one;");
                        code.Line("if ( __comma < 0 ) { break; }");
                        code.Line("name = name[( __comma + 1 )..];");
                    }

                    code.Line($"key = global::System.Runtime.CompilerServices.Unsafe.BitCast<{underlying}, {type}>(unchecked(({underlying})__bits));");
                    code.Line("return true;");
                }
                else
                {
                    code.Line($"if ( TryParseOne(name, out ulong __one) ) {{ key = global::System.Runtime.CompilerServices.Unsafe.BitCast<{underlying}, {type}>(unchecked(({underlying})__one)); return true; }}");
                    code.Line("return TryParseNumber(name, out key);");
                }
            }

            code.Line();

            using ( code.Block("private static bool TryParseOne( global::System.ReadOnlySpan<char> name, out ulong bits )") )
            {
                using ( code.Block("switch ( name )") )
                {
                    foreach ( EnumMemberInfo member in members ) { code.Line($"case {Naming.Literal(member.JsonName)}: bits = {Emitter.Number(member.Bits)}UL; return true;"); }
                }

                code.Line("bits = 0;");
                code.Line("return false;");
            }

            code.Line();

            using ( code.Block($"private static bool TryParseNumber( global::System.ReadOnlySpan<char> text, out {type} value )") )
            {
                code.Line("value = default;");
                code.Line($"if ( !{underlying}.TryParse(text, global::System.Globalization.NumberStyles.AllowLeadingSign, global::System.Globalization.CultureInfo.InvariantCulture, out {underlying} __number) ) {{ return false; }}");
                code.Line($"value = global::System.Runtime.CompilerServices.Unsafe.BitCast<{underlying}, {type}>(__number);");
                code.Line("return true;");
            }
        }

        code.Line();
    }
}
