global using System;
global using System.IO;
global using System.Text;
global using System.Text.Encodings.Web;
global using System.Text.RegularExpressions;
global using System.Text.Unicode;
global using System.Data;
global using System.Net;
global using System.Reflection;
global using System.Globalization;
global using System.Diagnostics;
global using System.Linq;
global using System.ComponentModel;
global using System.Security.Cryptography;
global using System.Runtime.CompilerServices;
global using System.Runtime.Serialization;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.Collections.Specialized;
global using System.Collections.ObjectModel;
global using System.Diagnostics.CodeAnalysis;
global using System.Threading;
global using System.Threading.Tasks;
global using System.ComponentModel.DataAnnotations;
global using Dapper;
global using Dapper.Contrib.Extensions;
global using Jakar.Extensions;
global using Jakar.Extensions.Xamarin.Forms;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using System.Drawing;
global using Nito.Collections;
global using KeyAttribute = Dapper.Contrib.Extensions.KeyAttribute;
global using JetBrains.Annotations;
global using Xamarin.Forms;
global using Xamarin.Forms.Xaml;
global using TypeConverter = Xamarin.Forms.TypeConverter;
global using TypeConverterAttribute = Xamarin.Forms.TypeConverterAttribute;
global using Color = Xamarin.Forms.Color;
global using Size = Xamarin.Forms.Size;
