// Jakar.Extensions :: Jakar.Extensions
// 07/30/2025  14:40

namespace Jakar.Extensions;


/// <summary> A simple source of information generated by Serilog itself, for example when exceptions are thrown and caught internally. </summary>
public static class SelfLogger
{
    private const           int                                                                      TIMESTAMP_LENGTH   = 29; // "yyyy-MM-ddTHH:mm:ss.fffffffZ" + ' '
    private const           int                                                                      MAX_CACHED_FORMATS = 128;
    private static readonly ConcurrentDictionary<string, string>                                     __formats          = new(StringComparer.Ordinal);
    private static readonly ConcurrentDictionary<string, string>.AlternateLookup<ReadOnlySpan<char>> __formatLookup     = __formats.GetAlternateLookup<ReadOnlySpan<char>>();
    private static          int                                                                      __formatCount;
    private static          Action<string>?                                                          __output;


    /// <summary> An <see cref="SelfLogFailureListener"/> that writes diagnostic information to <see cref="SelfLogger"/>. Sinks that support failure listeners should use this instance by default. </summary>
    public static SelfLogFailureListener FailureListener { get; set; } = new();


    /// <summary> Set the output mechanism for self-log messages to <see cref="Console.Error"/> </summary>
    public static void Enable() => Enable(Console.Error);


    /// <summary> Set the output mechanism for self-log messages. </summary>
    /// <param name="output"> An action to invoke with self-log messages. </param>
    /// // ReSharper disable once MemberCanBePrivate.Global
    /// <exception cref="ArgumentNullException"> When <paramref name="output"/> is <code>null</code> </exception>
    public static void Enable( Action<string> output ) => __output = ThrowIfNull(output);


    /// <summary> Set the output mechanism for self-log messages. </summary>
    /// <param name="output"> A synchronized <see cref="TextWriter"/> to which self-log messages will be written. </param>
    /// <exception cref="ArgumentNullException"> When <paramref name="output"/> is <code>null</code> </exception>
    public static void Enable( TextWriter output )
    {
        ArgumentNullException.ThrowIfNull(output);

        Enable(m =>
               {
                   output.WriteLine(m);
                   output.Flush();
               });
    }


    /// <summary> Clear the output mechanism and disable self-log events. </summary>
    /// // ReSharper disable once MemberCanBePrivate.Global
    public static void Disable() => __output = null;


    public static void WriteLine( string message )
    {
        Debug.WriteLine(EMPTY);
        Debug.WriteLine(message);
        Debug.WriteLine(EMPTY);

        __output?.Invoke(message);
    }

    // ReSharper disable once ExceptionLoggedAsTextProblem
    public static void WriteLine( Exception e ) => WriteLine("{Error} \n {StackTrace}", e.Message, e.ToString());


    public static void WriteLine<TArg0>( [StructuredMessageTemplate]                             string format, TArg0 arg0 )                                                 => WriteLine(Render(format, arg0));
    public static void WriteLine<TArg0, TArg1>( [StructuredMessageTemplate]                      string format, TArg0 arg0, TArg1 arg1 )                                     => WriteLine(Render(format, arg0, arg1));
    public static void WriteLine<TArg0, TArg1, TArg2>( [StructuredMessageTemplate]               string format, TArg0 arg0, TArg1 arg1, TArg2 arg2 )                         => WriteLine(Render(format, arg0, arg1, arg2));
    public static void WriteLine<TArg0, TArg1, TArg2, TArg3>( [StructuredMessageTemplate]        string format, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3 )             => WriteLine(Render(format, arg0, arg1, arg2, arg3));
    public static void WriteLine<TArg0, TArg1, TArg2, TArg3, TArg4>( [StructuredMessageTemplate] string format, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4 ) => WriteLine(Render(format, arg0, arg1, arg2, arg3, arg4));


    internal static string Render( string format )
    {
        Args0 args = new();
        return RenderCore(format, ref args);
    }
    internal static string Render<TArg0>( string format, TArg0 arg0 )
    {
        Args1<TArg0> args = new(arg0);
        return RenderCore(format, ref args);
    }
    internal static string Render<TArg0, TArg1>( string format, TArg0 arg0, TArg1 arg1 )
    {
        Args2<TArg0, TArg1> args = new(arg0, arg1);
        return RenderCore(format, ref args);
    }
    internal static string Render<TArg0, TArg1, TArg2>( string format, TArg0 arg0, TArg1 arg1, TArg2 arg2 )
    {
        Args3<TArg0, TArg1, TArg2> args = new(arg0, arg1, arg2);
        return RenderCore(format, ref args);
    }
    internal static string Render<TArg0, TArg1, TArg2, TArg3>( string format, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3 )
    {
        Args4<TArg0, TArg1, TArg2, TArg3> args = new(arg0, arg1, arg2, arg3);
        return RenderCore(format, ref args);
    }
    internal static string Render<TArg0, TArg1, TArg2, TArg3, TArg4>( string format, TArg0 arg0, TArg1 arg1, TArg2 arg2, TArg3 arg3, TArg4 arg4 )
    {
        Args5<TArg0, TArg1, TArg2, TArg3, TArg4> args = new(arg0, arg1, arg2, arg3, arg4);
        return RenderCore(format, ref args);
    }


    /// <summary>
    ///     Renders a message template (<c>{Name}</c>, <c>{@Name}</c>, <c>{$Name}</c>, <c>{Name,alignment:format}</c> or <c>{0}</c>) prefixed with a UTC timestamp.
    ///     Named holes take arguments in order, numeric holes by index, and <c>{{</c>/<c>}}</c> are escapes. Holes without a matching argument are written as-is; this never throws.
    /// </summary>
    /// <remarks>
    ///     <typeparamref name="TArgs"/> is a struct, so each argument count gets its own specialized code and every argument is appended through <see cref="DefaultInterpolatedStringHandler.AppendFormatted{T}(T, int, string?)"/> without boxing.
    ///     <paramref name="args"/> is passed by <see langword="ref"/>: an <see langword="in"/> parameter is defensively copied before every <see cref="ITemplateArgs.Append"/> call
    ///     (the compiler cannot prove an interface method on a generic struct is readonly), and passing by value measured ~40% slower (the struct is copied and passed by hidden reference anyway).
    /// </remarks>
    private static string RenderCore<TArgs>( string format, ref TArgs args )
        where TArgs : struct, ITemplateArgs
    {
        DefaultInterpolatedStringHandler builder = new(format.Length + TIMESTAMP_LENGTH, TArgs.Count);
        builder.AppendFormatted(DateTime.UtcNow, "o");
        builder.AppendLiteral(" ");

        ReadOnlySpan<char> span = format;
        int                next = 0;

        while ( !span.IsEmpty )
        {
            int brace = span.IndexOfAny('{', '}');

            if ( brace < 0 )
            {
                builder.AppendFormatted(span);
                break;
            }

            if ( brace > 0 ) { builder.AppendFormatted(span[..brace]); }

            span = span[brace..];

            // "{{" and "}}" are escapes; a lone "}" is literal.
            if ( span.Length > 1 && span[1] == span[0] )
            {
                builder.AppendFormatted(span[..1]);
                span = span[2..];
                continue;
            }

            int end = span[0] == '{'
                          ? span.IndexOf('}')
                          : -1;

            if ( end < 0 )
            {
                builder.AppendFormatted(span[..1]);
                span = span[1..];
                continue;
            }

            ReadOnlySpan<char> hole = span[1..end];
            if ( !hole.IsEmpty && hole[0] is '@' or '$' ) { hole = hole[1..]; }

            ReadOnlySpan<char> holeFormat = default;
            int                colon      = hole.IndexOf(':');

            if ( colon >= 0 )
            {
                holeFormat = hole[( colon + 1 )..];
                hole       = hole[..colon];
            }

            int alignment = 0;
            int comma     = hole.IndexOf(',');

            if ( comma >= 0 )
            {
                _    = int.TryParse(hole[( comma + 1 )..], NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out alignment);
                hole = hole[..comma];
            }

            int index = int.TryParse(hole, NumberStyles.None, CultureInfo.InvariantCulture, out int position)
                            ? position
                            : next++;

            if ( (uint)index < (uint)TArgs.Count )
            {
                args.Append(ref builder,
                            index,
                            alignment,
                            holeFormat.IsEmpty
                                ? null
                                : GetFormat(holeFormat));
            }
            else { builder.AppendFormatted(span[..( end + 1 )]); }

            span = span[( end + 1 )..];
        }

        return builder.ToStringAndClear();
    }


    /// <summary> Hole formats (e.g. <c>N2</c> in <c>{Elapsed:N2}</c>) come from constant templates, so they are cached and looked up by span to avoid allocating one per call. The cache is bounded. </summary>
    private static string GetFormat( ReadOnlySpan<char> format )
    {
        if ( __formatLookup.TryGetValue(format, out string? cached) ) { return cached; }

        string value = format.ToString();
        if ( Volatile.Read(ref __formatCount) < MAX_CACHED_FORMATS && __formats.TryAdd(value, value) ) { Interlocked.Increment(ref __formatCount); }

        return value;
    }


    /// <summary> Appends one argument. Strings (which ignore format strings) are copied directly; everything else goes through the generic, non-boxing path. </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)] private static void AppendArgument<T>( ref DefaultInterpolatedStringHandler builder, T value, int alignment, string? format )
    {
        if ( alignment      != 0 ) { builder.AppendFormatted(value, alignment, format); }
        else if ( typeof(T) == typeof(string) ) { builder.AppendFormatted(Unsafe.As<T, string?>(ref value)); }
        else { builder.AppendFormatted(value, format); }
    }



    private interface ITemplateArgs
    {
        abstract static int  Count { get; }
        public          void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format );
    }



    private readonly struct Args0 : ITemplateArgs
    {
        public static int  Count                                                                                            => 0;
        public        void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format ) { }
    }



    private readonly struct Args1<T0>( T0 arg0 ) : ITemplateArgs
    {
        public static int  Count                                                                                            => 1;
        public        void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format ) => AppendArgument(ref builder, arg0, alignment, format);
    }



    private readonly struct Args2<T0, T1>( T0 arg0, T1 arg1 ) : ITemplateArgs
    {
        public static int Count => 2;
        public void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format )
        {
            if ( index == 0 ) { AppendArgument(ref builder, arg0, alignment, format); }
            else { AppendArgument(ref builder,              arg1, alignment, format); }
        }
    }



    private readonly struct Args3<T0, T1, T2>( T0 arg0, T1 arg1, T2 arg2 ) : ITemplateArgs
    {
        public static int Count => 3;
        public void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format )
        {
            switch ( index )
            {
                case 0:
                    AppendArgument(ref builder, arg0, alignment, format);
                    return;

                case 1:
                    AppendArgument(ref builder, arg1, alignment, format);
                    return;

                default:
                    AppendArgument(ref builder, arg2, alignment, format);
                    return;
            }
        }
    }



    private readonly struct Args4<T0, T1, T2, T3>( T0 arg0, T1 arg1, T2 arg2, T3 arg3 ) : ITemplateArgs
    {
        public static int Count => 4;
        public void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format )
        {
            switch ( index )
            {
                case 0:
                    AppendArgument(ref builder, arg0, alignment, format);
                    return;

                case 1:
                    AppendArgument(ref builder, arg1, alignment, format);
                    return;

                case 2:
                    AppendArgument(ref builder, arg2, alignment, format);
                    return;

                default:
                    AppendArgument(ref builder, arg3, alignment, format);
                    return;
            }
        }
    }



    private readonly struct Args5<T0, T1, T2, T3, T4>( T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4 ) : ITemplateArgs
    {
        public static int Count => 5;
        public void Append( ref DefaultInterpolatedStringHandler builder, int index, int alignment, string? format )
        {
            switch ( index )
            {
                case 0:
                    AppendArgument(ref builder, arg0, alignment, format);
                    return;

                case 1:
                    AppendArgument(ref builder, arg1, alignment, format);
                    return;

                case 2:
                    AppendArgument(ref builder, arg2, alignment, format);
                    return;

                case 3:
                    AppendArgument(ref builder, arg3, alignment, format);
                    return;

                default:
                    AppendArgument(ref builder, arg4, alignment, format);
                    return;
            }
        }
    }



    public class SelfLogFailureListener
    {
        // The messages are built directly with interpolation (generic appends, no boxing). They were previously passed through string.Format,
        // which re-parsed the already-interpolated text and threw FormatException whenever the message or exception contained '{' or '}'.
        // A null interpolation hole appends nothing, so "{newLine}{exception}" disappears when there is no exception.
        public virtual void OnLoggingFailed<TKind>( object sender, TKind kind, string message, Exception? exception ) => WriteLine($"{DateTime.UtcNow:o} {sender.GetType()}: {message} ({kind}){NewLineIf(exception)}{exception}");


        public virtual void OnLoggingFailed<TKind, TLogEvent>( object sender, TKind kind, string message, IReadOnlyCollection<TLogEvent>? events, Exception? exception )
        {
            Action<string>? action = __output;

            action?.Invoke(events is not null
                               ? $"{DateTime.UtcNow:o} {sender.GetType()}: {message} ({kind}, {events.Count} events){NewLineIf(exception)}{exception}"
                               : $"{DateTime.UtcNow:o} {sender.GetType()}: {message} ({kind}, unspecified events){NewLineIf(exception)}{exception}");
        }


        protected static string? NewLineIf( Exception? exception ) => exception is null
                                                                          ? null
                                                                          : Environment.NewLine;
    }
}
