// Jakar.Extensions :: Jakar.Extensions
// 04/10/2024  23:04

namespace Jakar.Extensions;


public interface IErrorDetails
{
    /// <summary> A human-readable explanation specific to this occurrence of the problem. </summary>
    string? Detail { get; }


    StringTags? Errors { get; }

    /// <summary> A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. </summary>
    string? Instance { get; }

    /// <summary> The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem. </summary>
    Status? StatusCode { get; }

    /// <summary> A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization(e.g., using proactive content negotiation; see[RFC7231], Section 3.4). </summary>
    string? Title { get; }

    /// <summary> A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provides human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028]). When this member is not present, its value is assumed to be "about:blank". </summary>
    string? Type { get; }
}
